AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GraphQL:
    Properties:
      CodeUri: s3://artsy-lambda-deployments/8e78cb55698492a53f0839854abcc334
      Events:
        AnyRequest:
          Properties:
            Method: ANY
            Path: /graphql
          Type: Api
      Handler: graphql.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
